baseurl = "www.horangi.games"
languageCode = "en-us"
title = "Horangi"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Horangi Inc."
	description = "Game Development Company"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Horangi"

		[params.navigation.links]
			about     = "About"
			services  = "Team Squad"
			portfolio = "Games"
			contact   = "Contact"


	# 메인화면 
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "The Passionate Nerds"
		subtitle   = "Constantly challenging for a grand ambition, Making followers without following the ordinary path"
		buttonText = "Find out More"


	#  회사설명
	[params.about]
		headline    = "Horangi Inc."
		description = "Young villains who make games in South Korea."
		#buttonText  = "Get started!"


	# 팀 스쿼드
	[params.services]
		headline = "Team Squad"

        [[params.services.list]]
            icon = "fa-user"
            title = "Inwoo Baek"
            description = "Designer"

	[[params.services.list]]
	icon = "fa-user"
	title = "Kyu-Hwan Lee"
	description = "Artist"



    # 포트폴리오
	[params.portfolio.modal]
        client = "Download"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Let's play with Horangi games"

		#[params.aside.button]
		#	text = "Download now"
		#	link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "+82 10 6291 0779"
		email = "horang2game@gmail.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
